{
    "name":"Auction",
    "author":"Deepak R,Abhishek MH",
    "license":"LGPL-3",
    "version":"18.0.1.0",
    "sequence":"3",
    'depends': ['web','base','mail','bus'],
    "data":[
        "security/ir.model.access.csv",
        "data/cron.xml",
        "data/confirm_email.xml",
        "views/asset_category.xml",
        "views/new_property.xml",
        "views/new_auction.xml",
        "views/emd_views.xml",
        "views/bid_logs.xml",
        "views/bid_rules_view.xml",
        "views/auction_user_views.xml",
        "views/template/home.xml",
        "views/template/profile.xml",
        "views/template/payment.xml",
        "views/template/filters.xml",
        "views/template/completed_auctions.xml",
        "views/template/auctions_filters.xml",
        "views/template/detail.xml",
        "views/template/auction_table.xml",
        "views/template/reset_password.xml",
        "views/template/user_registration.xml",
        "views/template/login.xml",
        "views/template/hello.xml",
        "views/template/properties.xml",
        "views/template/auction.xml",
        "views/menu.xml",
    ],

    # 'assets': {
    #         'web.assets_frontend': [
    #             'auction_management/static/src/js/real.js',
    #         ],
    #     },

    "installable":True,
    "application":True,
    "auto_install":False,
}